/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Blue_Button: typeof import('./components/Blue_Button.vue')['default']
    Glass: typeof import('./components/glass.vue')['default']
    P: typeof import('./components/p.vue')['default']
    Purple: typeof import('./components/purple.vue')['default']
    Purpul: typeof import('./components/purpul.vue')['default']
    RED_Button: typeof import('./components/RED_Button.vue')['default']
    Simple_button: typeof import('./components/simple_button.vue')['default']
    Squircle: typeof import('./components/Squircle.vue')['default']
  }
}
